### ISSUE TITLE
LoadError with 'miga init' during install from source

### ISSUE THREAD

**Issue by ZoeHansen** [bio-miga/miga#112] opened 2020-08-12 20:58 UTC
I'm having a very similar issue to that mentioned in #96 , although I got MiGA from source (not using gems) and am not using conda (I used Homebrew to install requirements). I wasn't sure how to proceed here since many of the suggestions are specific to conda in the previous issue. 

When I attempt 'miga init' I am receiving the following error: 

`Traceback (most recent call last):
        14: from /mnt/home/USER/miga/bin/miga:7:in <main>
        13: from /opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
        12: from /opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
        11: from /mnt/ufs18/home-035/USER/miga/lib/miga.rb:7:in <top (required)>
        10: from /opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
         9: from /opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
         8: from /mnt/ufs18/home-035/USER/miga/lib/miga/project.rb:4:in <top (required)>
         7: from /opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
         6: from /opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
         5: from /mnt/ufs18/home-035/USER/miga/lib/miga/dataset.rb:7:in <top (required)>
         4: from /opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
         3: from /opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
         2: from /mnt/ufs18/home-035/USER/miga/lib/miga/dataset/result.rb:1:in <top (required)>
         1: from /opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require
/opt/software/Ruby/2.6.3-GCCcore-8.2.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require: cannot load such file -- sqlite3 (LoadError)`

I tried following along the suggestions in issue 96 by using the "gem install bundler" to identify if json was also my issue. I was able to successfully complete this code when designating a locally installed version of Ruby (2.7.1). 

I also attempted to run the "gem install miga-base" command while designating Ruby 2.7.1, but it threw another error: 

`Building native extensions. This could take a while...
ERROR:  Error installing miga-base:
        ERROR: Failed to build gem native extension.`

`current directory: /mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sqlite3-1.4.2/ext/sqlite3`

`/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/bin/ruby -I /mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/2.7.0 -r ./siteconf20200812-32184-aepne9.rb extconf.rb`
`*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.`

`Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/bin/$(RUBY_BASE_NAME)
        --with-sqlcipher
        --without-sqlcipher
        --with-sqlite3-config
        --without-sqlite3-config
        --with-pkg-config
        --without-pkg-config`
`/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:471:in try_do: The compiler failed to generate an executable file. (RuntimeError)`
`You have to install development tools first.
        from /mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:564:in try_link0
        from /mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:582:in try_link
        from /mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:684:in try_ldflags
        from /mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:1851:in pkg_config
        from extconf.rb:35:in <main>`

`To see why this extension failed to compile, please check the mkmf.log which can be found here:`

  `/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/sqlite3-1.4.2/mkmf.log`

`extconf failed, exit code 1`

`Gem files will remain installed in /mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sqlite3-1.4.2 for inspection.`
`Results logged to /mnt/ufs18/home-035/hansenzo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/sqlite3-1.4.2/gem_make.out`

My ~/.miga_modules file seems to be working without issue. But I can't seem to figure out what's needed to move forward/address the 'miga init' error. It's possible I'm just having trouble using/calling the correct Ruby version to use in my local directory?? Or overlooking other dependencies? 

Any help is appreciated! Thanks!

**Comment by lmrodriguezr** [comment] 2020-08-12 21:26
Hello @ZoeHansen,

When you got MiGA from source, did you follow the instructions [here](https://manual.microbial-genomes.org/part2/installation#getting-miga-source)?

It looks like the problem is when installing the `sqlite3` gem, but if you followed the instructions this should have been installed on the `bundle` step.

Regardless, it appears you're having issues installing that gem anyway (so the `bundle` step would have failed too). I recommend filing a bug report at [sparklemotion/sqlite3-ruby](/sparklemotion/sqlite3-ruby). However, I'll try to solve this issue from here as well:

1. What's your OS? I imagine you're using Linuxbrew based on the paths, but just to confirm.
2. Do you have SQLite3 installed (including developer libraries)? This should have been resolved by brew, but I had to do this manually in the [Google Collab notebook](https://colab.research.google.com/drive/1Wv4uZwLGuzc5RiAT8NkgJ6B_IKAeM0KU) (see first line)
3. What are the contents of the file `/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/sqlite3-1.4.2/mkmf.log`?

**Comment by ZoeHansen** [comment] 2020-08-12 22:12
@lmrodriguezr Thanks for getting back to me! 

I did follow those install instructions, and tried to bypass the bundle command since it wasn't working (sorry!). 

**1)** I am using CentOS Linux and had tried installing Homebrew to follow the recommended method for adding requirements. 
**2)** It looks like SQLite3 is installed in my .linuxbrew/bin/ directory. I'm not sure about the developer libraries -- I tried using the code from the Google Collab Notebook with 'brew install' (though I'm not sure I've entered it correctly): 

`brew install libsqlite3-dev > /dev/null`

and I'm given the error: 
Error: No available formula with the name "libsqlite3-dev"
Error: No previously deleted formula found.
Error: No similarly named formulae found.

Is there a source I need to designate in order to install these libraries? Or should they be recognized? 

**3)** My mkmf.log file contains the following: 
`"pkg-config --exists sqlite3"
| pkg-config --libs sqlite3
=> "-L/mnt/ufs18/home-035/USER/.linuxbrew/Cellar/sqlite/3.32.3/lib -lsqlite3\n"
"gcc -o conftest -I/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/include/ruby-2.7.0/x86_64-linux -I/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/include/ruby-2.7.0/ruby/backward -I/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/include/ruby-2.7.0 -I. -I/mnt/home/hansenzo/.rbenv/versions/2.7.1/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wno-maybe-uninitialized  -fPIC conftest.c  -L. -L/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib -Wl,-rpath,/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib -L. -L/mnt/home/USER/.rbenv/versions/2.7.1/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib -L/mnt/ufs18/home-035/USER/.rbenv/versions/2.7.1/lib -lruby  -lm   -lc"
//mnt/ufs18/home-035/USER/.linuxbrew/lib/librt.so.1: undefined reference to __libc_pread@GLIBC_PRIVATE'
//mnt/ufs18/home-035/USER/.linuxbrew/lib/librt.so.1: undefined reference to __recv@GLIBC_PRIVATE'
//mnt/ufs18/home-035/USER/.linuxbrew/lib/libpthread.so.0: undefined reference to __twalk@GLIBC_PRIVATE'
//mnt/ufs18/home-035/USER/.linuxbrew/lib/libpthread.so.0: undefined reference to __tsearch@GLIBC_PRIVATE'
//mnt/ufs18/home-035/USER/.linuxbrew/lib/libpthread.so.0: undefined reference to __tfind@GLIBC_PRIVATE'
//mnt/ufs18/home-035/USER/.linuxbrew/lib/librt.so.1: undefined reference to __socket@GLIBC_PRIVATE'
//mnt/ufs18/home-035/USER/.linuxbrew/lib/libpthread.so.0: undefined reference to __libc_vfork@GLIBC_PRIVATE'
//mnt/ufs18/home-035/USER/.linuxbrew/lib/libpthread.so.0: undefined reference to __call_tls_dtors@GLIBC_PRIVATE'
//mnt/ufs18/home-035/USER/.linuxbrew/lib/libpthread.so.0: undefined reference to __tdelete@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
`
I wasn't sure how to interpret this either, so any insight would be great!

Thank you, again, for getting back to me. I really appreciate it!

**Comment by lmrodriguezr** [comment] 2020-08-12 22:22
Yes, it looks like you have the binaries for SQLite3 but not the developer libraries. The Google Collab notebook uses `apt-get` to install those. I think in CentOS you'd have to use `yum`. I'm not very familiar with `yum`, but I think you can get the library using [the answer here](https://stackoverflow.com/questions/42669368/install-sqlite3-dev-and-other-packages-in-centos).

**Comment by ZoeHansen** [comment] 2020-08-12 23:04
Okay, I've tried using `yum install` to get the libraries but am having some trouble with this -- it might be due to permissions/limitations of our HPC. But thank you for pointing me in the right direction, I'll try to figure it out/get some help from our core to move forward. 

I really appreciate you taking time to explain a slightly-unrelated issue! Thanks!

**Comment by lmrodriguezr** [comment] 2020-08-13 00:08
Hi again,

I actually just found a way to link to the headers in your Homebrew installation:

```bash
gem install sqlite3 -- --with-sqlite3-dir="$(brew --cellar sqlite3)/$(brew list --versions sqlite3 | tr ' ' '\n' | tail -n 1)"
```

I'll update the documentation soon, but for now this should do the trick.

**Comment by lmrodriguezr** [comment] 2020-08-13 00:37
Documented in 7432f6fd5802f5907d3d51103fb9a0ffb9dff9e7

Please feel free to reopen if this solution didn't work for you

**Closed by lmrodriguezr** 2020-08-13 00:37 UTC
