### ISSUE TITLE
adding a query dataset does not work

### ISSUE THREAD

**Issue by thomasvangurp** [bio-miga/miga#87] opened 2019-12-12 13:24 UTC
I am running `MiGA 0.4.3.1 - aquatint - 2019-09-16` when I try to add a query dataset i get an error:
the script(s) try to read from a tmp file that does not exist:

```
(miga) thomas@NAK-Test-01:/opt/miga/miga$ ./bin/miga add  -P /opt/miga/miga-data/test/ -D Xanthomonas_hortorum_pv_pelargonii_NBC631 -t genome --query --description "Test Query" -i assembly "/6_db_ssd/primer_tool/Xanthomonas/internal/NBC-631_Xanthomonas_hortorum_pv._pelargo
nii.fna.gz" --debug 2
Metadata.save /opt/miga/miga-data/test/metadata/Xanthomonas_hortorum_pv_pelargonii_NBC631.json
     /5_workspace/repos/miga/lib/miga/metadata.rb:58:in `save'
     /5_workspace/repos/miga/lib/miga/metadata.rb:52:in `create'
     /5_workspace/repos/miga/lib/miga/metadata.rb:37:in `initialize'
     /5_workspace/repos/miga/lib/miga/dataset.rb:58:in `new'
     /5_workspace/repos/miga/lib/miga/dataset.rb:58:in `initialize'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:152:in `new'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:152:in `create_dataset'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:65:in `block in perform'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:64:in `each'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:64:in `perform'
     /5_workspace/repos/miga/lib/miga/cli/action.rb:32:in `launch'
     /5_workspace/repos/miga/lib/miga/cli.rb:170:in `launch'
     ./bin/miga:10:in `<main>'
Metadata.save /opt/miga/miga-data/test/metadata/Xanthomonas_hortorum_pv_pelargonii_NBC631.json
     /5_workspace/repos/miga/lib/miga/metadata.rb:58:in `save'
     /5_workspace/repos/miga/lib/miga/dataset.rb:68:in `save'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:69:in `block in perform'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:64:in `each'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:64:in `perform'
     /5_workspace/repos/miga/lib/miga/cli/action.rb:32:in `launch'
     /5_workspace/repos/miga/lib/miga/cli.rb:170:in `launch'
     ./bin/miga:10:in `<main>'
Metadata.save /opt/miga/miga-data/test/miga.project.json
     /5_workspace/repos/miga/lib/miga/metadata.rb:58:in `save'
     /5_workspace/repos/miga/lib/miga/project.rb:69:in `save!'
     /5_workspace/repos/miga/lib/miga/project.rb:63:in `save'
     /5_workspace/repos/miga/lib/miga/project/dataset.rb:57:in `add_dataset'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:70:in `block in perform'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:64:in `each'
     /5_workspace/repos/miga/lib/miga/cli/action/add.rb:64:in `perform'
     /5_workspace/repos/miga/lib/miga/cli/action.rb:32:in `launch'
     /5_workspace/repos/miga/lib/miga/cli.rb:170:in `launch'
     ./bin/miga:10:in `<main>'
Exception: No such file or directory @ rb_sysopen - /tmp/MiGA.gz20191212-40754-w7chia

DEBUG: /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `initialize'
DEBUG: /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
DEBUG: /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
DEBUG: /usr/lib/ruby/2.3.0/fileutils.rb:486:in `copy_file'
DEBUG: /usr/lib/ruby/2.3.0/fileutils.rb:403:in `block in cp'
DEBUG: /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
DEBUG: /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
DEBUG: /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
DEBUG: /usr/lib/ruby/2.3.0/fileutils.rb:402:in `cp'
DEBUG: /5_workspace/repos/miga/lib/miga/common/format.rb:53:in `clean_fasta_file'
DEBUG: /5_workspace/repos/miga/lib/miga/dataset/result.rb:201:in `add_result_assembly'
DEBUG: /5_workspace/repos/miga/lib/miga/dataset/result.rb:52:in `add_result'
DEBUG: /5_workspace/repos/miga/lib/miga/dataset/result.rb:68:in `block in first_preprocessing'
DEBUG: /5_workspace/repos/miga/lib/miga/dataset/result.rb:67:in `each'
DEBUG: /5_workspace/repos/miga/lib/miga/dataset/result.rb:67:in `find'
DEBUG: /5_workspace/repos/miga/lib/miga/dataset/result.rb:67:in `first_preprocessing'
DEBUG: /5_workspace/repos/miga/lib/miga/cli/action/add.rb:71:in `block in perform'
DEBUG: /5_workspace/repos/miga/lib/miga/cli/action/add.rb:64:in `each'
DEBUG: /5_workspace/repos/miga/lib/miga/cli/action/add.rb:64:in `perform'
DEBUG: /5_workspace/repos/miga/lib/miga/cli/action.rb:32:in `launch'
DEBUG: /5_workspace/repos/miga/lib/miga/cli.rb:170:in `launch'
DEBUG: ./bin/miga:10:in `<main>'
```

**Comment by lmrodriguezr** [comment] 2019-12-27 22:45
Hello @thomasvangurp 
Thanks a lot for this detailed report!
I believe this was caused by a bug introduced around 0.4.3.0 that was already corrected. The issue was with cleaning FastA files on the fly when the input was gzipped.

This issue has now been resolved, please try again with the latest version (0.5 - collotype). I'll close this issue now, but please do not hesitate to reopen and/or open a new issue if you continue to experience this problem.

Best,
Miguel.

**Closed by lmrodriguezr** 2019-12-27 22:45 UTC
